### ISSUE TITLE
Mark Tiles In Volcano Dungeon

### ISSUE THREAD

**Issue by fz0308** [stardew-access/stardew-access#196]
I'm already at Volcano Mine 9, but I can't find my way to Volcano Mine 10 or the Caldera. Is there a way to remove blocks that are in the way?

**Comment by khanshoaib3** [comment]
I'm so sorry for replying late. I missed the notification.
Did you happen to have figured it out?

**Comment by khanshoaib3** [comment]
Oh and is this related to #190?

**Comment by fz0308** [comment]
Yes, but it's worse, because this not only infront the entrance, but also the path to reach the entrance

**Comment by khanshoaib3** [comment]
I see. Well I'll test out the level and get back to you soon.

**Comment by khanshoaib3** [comment]
@fz0308 So I tested the dungeon levels and seems that there are these pressure pads that needs to pushed in order to open the gate blocking the entrance to the next level.
Have already added those tiles so you should be able to reach Caldera from the next beta.
