### ISSUE TITLE
New Achievements Not Recognised In The Collections Tab

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#206]
The 1.6 update introduced quite a few new achievements that a farmer can earn. When you go to the collections tab above the inventory and select achievements, it reads all the old ones with gaps in between where the new ones would be.

**Comment by khanshoaib3** [comment]
The gap ones I think were the ones marked as `???`. So I've had them say unknown in the [latest](https://github.com/khanshoaib3/stardew-access/commit/dd22dabd181cf8d61d66a0f40702757b81d4b62c) commit. And also the unacheived ones now speak description as well.

Will close this issue once you confirm it as fixed :)
