### ISSUE TITLE
Co-ordinates in the buildings menu on the new farm type are broken

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#207]
When you try building on the meadowlands farm, and try to select a position for the building, the furthest co-ordinates the building map recognises is 64,51, but if you actually look on the farm the furthest co-ordinates are 91,59. This means that you can't build on a portion of the map.

**Comment by BrailleBennett** [comment]
This was revealed to be the fact that because the curser is locked to a specific spot on screen, you eventually pan to the edge of the map, but your curser is still stuck in it's locked position, leading to unexplorable tiles on the edges of the map. Effects all farm types.
