### ISSUE TITLE
Quarry Mine Entrance Needs Renaming

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#215]
The object tracker currently recognises the quarry mine entrance as just mine entrance, meaning that whenever you try to warp there it only takes you to the main mine entrance. This needs renaming to potentially something like Quarry Mine Entrance?
(Issue found by myself and @BrailleBennett)

**Comment by BrailleBennett** [comment]
This was revealed to be the fact that because the curser is locked to a specific spot on screen, you eventually pan to the edge of the map, but your curser is still stuck in it's locked position, leading to unexplorable tiles on the edges of the map. Effects all farm types.

**Comment by BrailleBennett** [comment]
Wrong issue, sorry
