### ISSUE TITLE
Tilled Dirt In Mine And  Skull Cavern Not Reading

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#219]
Since the 1.6 update, dirt that has been tilled in the mine or skull cavern doesn't read as anything. The tiles just say , and then the coordinates. 
(Issue found by myself and @BrailleBennett)

**Comment by khanshoaib3** [comment]
@LucieG0 Just checked and it is correctly reading untilled tiles as `dirt` and tilled ones as `soil`.
Maybe recheck this in the next beta.

**Comment by LucieG0** [comment]
This seems fixed in Beta 1.3

**Comment by BrailleBennett** [comment]
This issue can probably be closed since behavior now seems nominal with it.
