### ISSUE TITLE
bed interaction not working with different game language

### ISSUE THREAD

**Issue by falisca** [stardew-access/stardew-access#22]
Hi,

If I change the game language I'm unable to save the game because interacting with the bed simply doesn't work.
I tryed with US keyboard layout and I only changed the language in the game.
I suppose that this interaction was managed in the mod by a simple string association but diving into the code showed I was wrong. Please note that I doesn't know so much C# language.
Sudgestions?

**Comment by khanshoaib3** [comment]
@falisca  If you could post the log file, that would be super useful 🙂

**Comment by khanshoaib3** [comment]
@falisca Just checked the issue, and its caused by the Accessible Tiles mod, for now you can fix this by disabling the grid movement, i'll post this issue there.
