### ISSUE TITLE
Locked achievements are shown in full in collections

### ISSUE THREAD

**Issue by BrailleBennett** [stardew-access/stardew-access#226]
In 1.6, visually, the achievements in the collections menu show as ??? If they are still locked, as described in the patch notes, stardew access currently reads all achievements in their entirety, even if they're locked.

**Comment by khanshoaib3** [comment]
I think this is related to #206
So we'll need to re-verify it.

**Comment by BrailleBennett** [comment]
My intent behind this issue was to rename all of the achievements not unlocked to something like unknown achievement or locked achievement to better reflect the visual information provided to sighted players of the game.

**Comment by khanshoaib3** [comment]
@BrailleBennett Actually, the unachieved achievements are visually shown like the other unlocked ones.
The only difference is that the unachieved ones are greyed out.

**Comment by BrailleBennett** [comment]
Weird, I'm just going off of the patch note line under quality of life changes on the official patch notes:
The achievement menu now lists all potential achievements. Hidden achievements you haven’t unlocked yet are shown as “???”.
Source:
https://www.stardewvalley.net/stardew-valley-1-6-update-full-changelog/

**Comment by khanshoaib3** [comment]
@BrailleBennett Well, there probably are three types of achievements,
1. Unlocked and achieved, details spoken in full.
2. Unlocked but un-achieved, details spoken in full (just like visually it is fully visible) but with an un-achieved status.
3. Locked/Unknown ones, makred with `"???"`
