### ISSUE TITLE
Garden Pot Contents

### ISSUE THREAD

**Issue by Bartholomue** [stardew-access/stardew-access#23]
The contents and status of garden pots are undetected by Stardew Access. Even if a a garden pot has a plant, it's still just a garden pot. Could they be treated as trellis crops so you can see there fertilization status, moisture, crop, and crop state?

**Comment by khanshoaib3** [comment]
It should be an easy fix, will see what I can do, thanks

**Comment by khanshoaib3** [comment]
Turns out, it's not as easy as i thought.

**Comment by khanshoaib3** [comment]
Patched as of https://github.com/stardew-access/stardew-access/commit/9199d764ba46a09d00936902b54de4f5ec76acd5
