### ISSUE TITLE
Infinity weapon conversion progress isn't reported by Stardew access

### ISSUE THREAD

**Issue by BrailleBennett** [stardew-access/stardew-access#239]
When forging the galaxy sword with galaxy souls at the caldera or mini forge, it visually becomes more like the infinity blade for each galaxy soul you use. Stardew Access doesn't report this change, and still calls it a normal galaxy sword until it has fully transformed into the infinity blade. This also applies to galaxy dagger and galaxy hammer.

**Comment by khanshoaib3** [comment]
@BrailleBennett How should I convey the progress? I can get the level of enchantment which basically will be 1, 2 or 3.
Should it be like Galaxy Soul 50%?

**Comment by BrailleBennett** [comment]
I think that saying something like (transformation 33%) would be valid. E.G.: Galaxy Sword (transformation 33%)
Since it can only be 33% or 66% transformed. As you need 3 souls from not transformed at all to fully transformed into a completely different item. I wouldn't want to say infinity transfermation, as that's a spoiler for what the sword will transform into, and saying galaxy soul and then the percentage seems a little to vague, as visually the weapon is transforming.
