### ISSUE TITLE
Sign Contents Undetected

### ISSUE THREAD

**Issue by Bartholomue** [stardew-access/stardew-access#24]
Would it be possible to have Stardew Access announce the contents of a sign object? These are used as markers and displays, so it'd be very useful to have access to this information.

**Comment by khanshoaib3** [comment]
It's in my todo, I'll fix this soon, thanks.

**Comment by khanshoaib3** [comment]
Patched as of https://github.com/stardew-access/stardew-access/commit/949e5c5bfc3314f6cfef8e3a369fc50b6637e504
