### ISSUE TITLE
Informative Status Report

### ISSUE THREAD

**Issue by Bartholomue** [stardew-access/stardew-access#25]
Provide a hotkey to report the actual numerical values for your health and stamina. Change the current health/stamina report function so that it amends percent to the end of the report so that players know they're hearing a percentage, rather than a raw value.

**Comment by khanshoaib3** [comment]
How about a command to toggle between percentage and numeric health n stamina narration

**Comment by khanshoaib3** [comment]
Patched as of 408a40121d428ac82e212237378e1c3a90cc4d6e
