### ISSUE TITLE
Request: New Mannequin Items To Read The Clothing Items They Are Wearing

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#252]
The 1.6 update added mannequins so you can show off the clothes that you have, but they do not read what items you put on them. Request for a future update that they read the outfits? This is not a priority though.

**Comment by khanshoaib3** [comment]
@LucieG0 I'm adding the narration of items displayed on the mannequin and I'm basically just appending the names of the items to `Mannequin` separated by commas.
My question is that should I also have it narrate the direction mannequin is facing?
I feel like it will create an unnecessary translation entry.

**Comment by LucieG0** [comment]
I think this could potentially be useful though because most outfits have a front and back, and it'd be a bit pointless showing off all the styles if they're facing the wall if this makes sense?

**Comment by khanshoaib3** [comment]
Point. I'll have it say the facing directions as well, except when in default position i.e., looking south.
