### ISSUE TITLE
Speak the bubble text when interacting with pet bowl

### ISSUE THREAD

**Issue by khanshoaib3** [stardew-access/stardew-access#253]
When we interact with the pet bowl, it shows a bubble with the pet's name, like so, `Dudley's Bowl`.
Looked at the code and `SpriteText.drawSmallTextBubble()` is showing that text.
So we can either patch that method or `PetBowl.draw()`.

**Comment by BrailleBennett** [comment]
I wonder if just naming the bowl such and such's bowl would also be a viable solution.

**Comment by khanshoaib3** [comment]
The `drawSmallTextBubble()` could also be used by some other stuff so it's better to patch that.
Possible even that a mod uses it so we're not only patching pet bowl but other stuff too.

Also, we could per pend the pet's name to the bowl. It don't matter that much though I think, cause we can already distinguish them with their skin now.

**Comment by khanshoaib3** [comment]
I was right! This very method is used to display a bubble when the player hovers over a text sign.
So patching this will also make text signs accessible.

This method is also used in `DayTimeMoneyBox` menu but it hasn't been patched yet.

**Comment by BrailleBennett** [comment]
There's more pets than bowl skins though

**Comment by khanshoaib3** [comment]
Well, patching `drawSmallTextBubble()` cause it kept bugging out in case of multiple pet bowls or text signs.

So now, for pet bowl, whenever we interact with it, it will say the bubble text i.e. associated pet's name.

As for text signs, well, I've had it simply append the sign text. Visually, the bubble only appears when the player is within the 1 tile radius I think but implementing that will cause confusion when using OT.

> There's more pets than bowl skins though

I was rather thinking of pre-pending the pet bowl's type to make things more vanilla.
Well, we'll see things go in the 2nd beta and I'll edit it if needed.
