### ISSUE TITLE
items placed on top of other items are effectively invisible

### ISSUE THREAD

**Issue by lilmike** [stardew-access/stardew-access#258]
Hiya,

If you place an item on top of another item, for example a chest on top of a rug, the chest will be effectively invisible. Only knowing where it is without the list of items will let you interact with it.

-Michael.

**Comment by LucieG0** [comment]
Commented this under a related issue posted by Khai, but in case you get to this first I'll paste it here. A related problem is specifically when playing in co-op, the tiles that players are stood on are overwritten and masked. (Reported by @BrailleBennett ).

**Comment by khanshoaib3** [comment]
Closing this as it's a duplicate of #300
