### ISSUE TITLE
New Prize Machine In Mayor's House Is Inaccessible

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#259]
1.6 added a new prize machine in Lewis' house where you exchange tickets for prizes. This is currently inaccessible. The tile is tracked in one of the user tiles files submitted on another issue, but the machine itself is also not accessible with stardew-access. 
(Issue reported by discord user Khai)

**Comment by BrailleBennett** [comment]
Is the bobber machine also inaccessible in the fish shop?
