### ISSUE TITLE
1.6: unable to navigate to river fishing spot in town

### ISSUE THREAD

**Issue by danielw97** [stardew-access/stardew-access#261]
I'm using Stardew Valley 1.6.2, and have built Stardew Access from the dev branch Commit 35163b0.
Currently it isn't possible to navigate in town to the fishing spot defined at coordinates 94, 10.
Using the tile explorer it appears to be blocked by the Joja Bridge.

Let me know if there's any more info I can provide to troubleshoot this.
Thanks for your continued work on Stardew Access and supporting the 1.6 update so quickly.

**Comment by BrailleBennett** [comment]
Are you using auto walk, or manually moving with WASD? If using auto walk, it this may just be a case of issue #275.

**Comment by danielw97** [comment]
I observe this behavior manually walking as well, it seems as though the Joja bridge isn't able to be walked on for some reason and that is where the fishing spot in town is currently defined.
