### ISSUE TITLE
Grandpa's shrine candles aren't tracked

### ISSUE THREAD

**Issue by BrailleBennett** [stardew-access/stardew-access#265]
After year 3 when the candles are lit on the shrine on the farm, Stardew access currently has no way of reporting it. You don't know if you have 1, 2, or 3 candles.

**Comment by khanshoaib3** [comment]
@BrailleBennett I think this already works. What farm type are you testing it on? Currently it checks for 8x 7y for the shrine, maybe that's not the case in the farm type you're using.

**Comment by BrailleBennett** [comment]
I'm talking about the amount of candles lit on the shrine, yes, the shrine itself appears tracked, but from what I can tell, it is impossible to know if 1, 2, 3, or 4 candles are lit on it.

**Comment by khanshoaib3** [comment]
But I checked with year 4 save file, with all 4 candles and it did correctly speak the amount of lit candles.

**Comment by khanshoaib3** [comment]
@BrailleBennett Is this happening in beta v2.1?

**Comment by khanshoaib3** [comment]
Any update @BrailleBennett ?

**Comment by BrailleBennett** [comment]
Will retest on beta 2.4 or > to see if I can repro.
