### ISSUE TITLE
Informative Mill Tiles

### ISSUE THREAD

**Issue by Bartholomue** [stardew-access/stardew-access#27]
Consider labeling the bottom second (from the left) tile of the mill building as mill input to help people find where to put ingredients to be processed.
Also consider labeling the bottom right tile as mill output so players know this is what they have to interact with to receive products.
If it's possible to determine the property, label the mill as busy when it has contents to convert.

**Comment by khanshoaib3** [comment]
Patched as of f2d607484e36e68adc8fb00c9aa31e2a42fc7c0f
