### ISSUE TITLE
Home Cook's Community Centre Bundle Not Reading

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#276]
For some reason, the home cook's bundle in the mixed bundles version of the community centre seems not to read. It will also not let you press C or V to look at items or slots. 
(Issue reported by Peanut Pablo and tested by myself).

**Comment by khanshoaib3** [comment]
@LucieG0 So I created a new farm to test the remixed bundles and well, I can't get it to choose the home cook's bundle.
So can you maybe send your save file? That would help a lot :)

**Comment by LucieG0** [comment]
@khanshoaib3 I've sent it on discord :)
