### ISSUE TITLE
Dynamic Fish Pond Naming

### ISSUE THREAD

**Issue by Bartholomue** [stardew-access/stardew-access#28]
When you place a sign of the vessel on a fish pond, it shows what kind of fish you have in that fish pond. Can this be reflected with Stardew Access by changing the building name to incorporate the fish in its title? This would be similar to reading fish pond details with c while viewing a fish pond, where it says sturgeon fish pond.
Also display harvest / quest availability in the pond's object name, so that when you face a fish pond, it would say catfish fish pond (harvestable), rainbow troutch fish pond (quest), etc.

**Comment by khanshoaib3** [comment]
Patched as of 2df4cfca2737959914f9e37ae60981ff6516f9e8
