### ISSUE TITLE
Certain monster varients aren't recognized by the mod

### ISSUE THREAD

**Issue by BrailleBennett** [stardew-access/stardew-access#283]
Some visually distinct monster skins in the game aren't registered by Stardew Access. For example, in the bug layer in the suers, the bugs and grubs look disfigured and are referred to as mutant bugs and mutant grubs, the mod just reads these as bugs and grubs. In the mayors basement, when collecting a pair of shorts, a flying purple shorts monster will spawn, the game considers this to be a bat, so this is what stardew access reports, in levels 880 and above of the skull caverns, iridium bats turn red and have double health, but the mod just reads them as normal iridium bats.

**Comment by BrailleBennett** [comment]
Co-tested by @lucieg0

**Comment by BrailleBennett** [comment]
Adding on to this, the wiki lists all of the dangerous variants of monsters in the hard mode skull caverns and mines as separate enemy variants like the mutant enemies. However, Stardew Access doesn't change the name to add the word dangerous in front of them.

**Comment by BrailleBennett** [comment]
The red iridium bats also appear on farms with monsters enabled.

**Comment by ParadoxiKat** [comment]
The shorts have been fixed; looking into the bats and sewer bugs.
For the dangerous variants we should check if they're visually distinct on screen, and if there can be a mix of dangerous and non-dangerous monsters at the same time. If a dangerous mine level only has dangerous monsters, no possibility of a dangerous one side by side with a non-dangerous one -- then I say it's extra unnecessary info. If you know you're in dangerous mode, you know the monsters are dangerous -- unless there can be a mix of types, in which case I assume they are also visually distinctive.
