### ISSUE TITLE
Suggestion: Add A Repeat Text Feature

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#291]
It has been suggested that a feature is added to reread the text which was just spoken in case the player misses it, or in case an announcement was spoken over. Not a priority but would be nice.
(Suggested by Liam Erven)

**Comment by khanshoaib3** [comment]
Well, @BrailleBennet suggested to add tts history reading just notification/chat reading. So I guess this will be covered in that feature.
