### ISSUE TITLE
Lumber Pile On New MeadowLands Farm Marked Incorrectly

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#308]
Where the lumber pile is marked as a static tile to show up on the standard farm after completing QI's quest, the  location is wrong for the new farm type as the farmhouse and lumber pile is in a different place, so the object tracker just takes you to a random place on the farm.

**Comment by BrailleBennett** [comment]
Also, since we can move the farm house, this manually marked tile will always be wrong if farm house is moved on any type, dinamic detection of the woodpile must be added I think, assuming the wood pile moves with your house, which I'd assume it does.

**Comment by khanshoaib3** [comment]
Fixed this but since the pile is marked in Decor category, shouldn't this be visible all the time and not just during the quest?

**Comment by khanshoaib3** [comment]
@LucieG0 ^^

**Comment by LucieG0** [comment]
Perhaps have the log pile usually show up under decor until the quest, then move it to interactables once you have to get the thing out of it? Not sure if this makes sense, just an idea :)

**Comment by ParadoxiKat** [comment]
I second Lucie's idea with a minor adjustment. Always shows up in Decor category until the Qi quest, then it shows in Quest category. Once you interact with it and complete the quest it moves back to Decor.

**Comment by ParadoxiKat** [comment]
Marking for next (1.6) release as it's mostly done already and can be closed once it's properly categorized as Decor with temporary Quest category.
