### ISSUE TITLE
two animals categories exist in the tracker, one of which has phantom animals

### ISSUE THREAD

**Issue by lilmike** [stardew-access/stardew-access#310]
Just as the title says, when you are on the farm with some, but not all, animals, there are two animals categories, one with phantom animals.

-Michael.

**Comment by khanshoaib3** [comment]
Phantom animals? Do you mean out of bounds animals? @lilmike

**Comment by lilmike** [comment]
I'm not entirely sure. They show up in the animals category, and you can
even walk to them if I remember right, but they never seem to move and
you can't interact with them. You can also walk through them. This will
happen on sunny days when the animals are out, or on rainy days when the
animals are in doors just the phantom animals will show up outdoors.

-Michael.




On Thu, May 23, 2024 at 01:07:17PM -0700, Mohammad Shoaib Khan wrote:
>Phantom animals? Do you mean out of bounds animals? @lilmike
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/khanshoaib3/stardew-access/issues/310#issuecomment-2127934793
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

-- 
Sorry about the test, it's just a me thing.
Michael Taboada, Creator of Games. Does that make me a god, well, sorta.
My pgp key: 79BC390E8864CD71305D4DD606CD2197A6EE5ED7
My website: https://michaels.world
2MB website: https://2mb.games
Don't believe everything you read on the internet. I might not be real, you might not be real, and this email certainly isn't real.
Sent from my kitchen...
stationary bicycle

**Comment by khanshoaib3** [comment]
This has been fixed in #358 
Thank you 🙂
