### ISSUE TITLE
Naming Animals Menu In Marnies Seems A Bit Glitchy

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#312]
This menu still works so not an immediate priority, but seems to be a bit buggy once you pick the building to put the animal in. Specifically it's the part where you have to name the animal or pick a random name. It just glitches a bit and scrolling between options sometimes doesn't read.

**Comment by khanshoaib3** [comment]
@LucieG0 I can't re-create this bug and everything seems to be working well. So I suggest sending the log file, if it stops reading anything in the menu from a point on, then there's likely the patch throws an error or someting.

**Comment by LucieG0** [comment]
Seems to be better in latest update :)
