### ISSUE TITLE
Cellar Seems Broken In Latest Update

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#313]
The cellar seems completely not to be working in this latest update. Once you enter, the object tracker says that no items can be found, even if you refresh it, so you can't even locate the door to leave again. Moving around seems also potentially broken, taking you to tiles that are off the out of bounds. You also don't seem able to place any casks, or use any that are already placed.
(Parts of this issue reported by discord user Imaginatrix).

**Comment by BrailleBennett** [comment]
It really looks to me like the seller door is just warping us to an empty void map, or at least out of bounds, as this matches your symptoms perfectly.

**Comment by Shadowcat42** [comment]
This seems to be a case of Stardew Access reporting the wrong thing and teleporting you in a weird spot. At least in my case, the cellar entrance is just to the west of the farmhouse door and south. If I walk in through that way, everything's fine.
