### ISSUE TITLE
Likely A Typo In Project Fluent String Translation With Object Tracker

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#316]
Just opening a ticket for the discussed issue. Log sent in private messages. 
(Reported by discord user Khai).

**Comment by khanshoaib3** [comment]
@LucieG0 What's the typo?

**Comment by LucieG0** [comment]
If I'm totally honest I can't remember. I checked back through messages and can't see what this was about, note to self describe issues better, 🤦‍♀️ not sure if  @ParadoxiKat remembers, but If not then it can't be that big of an issue so we can close this as not planned?

**Comment by ParadoxiKat** [comment]
This will likely be reported again and fixed without us remembering what it was. If we do connect the dots we can always reopen and close it as completed.
