### ISSUE TITLE
Items renamed In Latest Update Still Read With Old Names

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#327]
1.6.4 renamed a few items that haven't been updated in Stardew Access. These items are: 

fern → fiddlehead fern

mushroom → red mushroom

mahogany → hardwood

**Comment by khanshoaib3** [comment]
@LucieG0 The patch notes say this:
> Shaving enchantment now causes tree-specific drops:
>    fern → fiddlehead fern
>    mushroom → red mushroom
>    mahogany → hardwood
Doesn't this mean that mahogany drops hardwood with shaving enchant?

**Comment by LucieG0** [comment]
This makes sense :)
