### ISSUE TITLE
The giant stump in the forest not tracked

### ISSUE THREAD

**Issue by fz0308** [stardew-access/stardew-access#329]
There is a page about the giant stump at the wiki. It located at the forest. When you interact with it, you will start a quest. But the giant stump is currently couldn't be track by the mod. Source: https://stardewvalleywiki.com/Giant_Stump

**Comment by LucieG0** [comment]
I believe this is marked on a previous tiles file I submitted. Coordinates 56:6.

**Comment by khanshoaib3** [comment]
@fz0308 I think I patched this in the 3rd beta (#216).
The stump will only show up after the thunderstorm.

**Comment by Shadowcat42** [comment]
Yes, once the storm has occurred, it should be there.
