### ISSUE TITLE
Detect Sprinkler Attachments

### ISSUE THREAD

**Issue by Bartholomue** [stardew-access/stardew-access#34]
The various sprinklers, which equipped with either a pressure nozzle or an enricher have different sprites. Could this be reflected with Stardew Access so we know which sprinklers are suitably upgraded?
Examples: pressurized [sprinkler name] and enriching [sprinkler name].

**Comment by khanshoaib3** [comment]
patched as of a908e098846db8c0069da02e6e270b2d82effa89
