### ISSUE TITLE
Distinguish Between Ladders and Shafts

### ISSUE THREAD

**Issue by Bartholomue** [stardew-access/stardew-access#35]
These two exit points work differently from one another and are visually distinct. Ladders give you a normal descent, but shafts can drop you multiple floors. Shafts will damage the player based on the number of floors bypassed. It's important to reflect the differences between these two objects so that players can formulate an educated exit strategy when traversing the already dangerous skull caverns.

**Comment by khanshoaib3** [comment]
Fixed as of d12e9b259041391fb28cca2b815cad413fc39147
