### ISSUE TITLE
Rows Of Inventory Show Even When Backpack Is Not Upgraded.

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#361]
When in a chest, or selling at a shop etc, the mod reads three rows of personal inventory regardless of whether or not you have purchased any of the backpack upgrades. I was wondering if it would be possible for it to only read the number of rows you actually have available to use?

**Comment by khanshoaib3** [comment]
Well this is tricky. As the mod does not provide the menu navigation, we can't really prevent the cursor from focusing on locked slots without changing some original code, specifically related to component ids.
And I don't want to mess with that, at least not for v1.6.0, we could experiment with it later.
So for now, should we instead have these slots speak "Locked"? @LucieG0

**Comment by khanshoaib3** [comment]
@LucieG0 ^^
