### ISSUE TITLE
Types Of Flooring Not Read Out

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#362]
Stardew-Access used to read out the different types of flooring, but no longer seems to, even when you edit the option for it to do so in the config. In particular, if you use any of the pathway recipes, it just reads as pathway, which is problematic if you want to know whether you're walking on a wooden or straw path. It would be useful for the mod to specify the type of path tile that has been placed, but with the functionality to configure it on/off using the read flooring option in the config.

**Comment by khanshoaib3** [comment]
@LucieG0 I suppose adding a new config to toggle descriptive flooring names would be the way to go.
So, I guess I'll add "DescriptiveFlooring" which will be enabled by default.

Edit: Will name it "DisableDescriptiveFlooring" to match other configs.
