### ISSUE TITLE
Suggestion: Add An Organise Inventory Hotkey

### ISSUE THREAD

**Issue by LucieG0** [stardew-access/stardew-access#364]
Not a priority, but to save scrolling across the entire inventory to find the organise inventory button, perhaps a keyboard hotkey could be implemented, like the delete key for trashing items. It would also be nice to have an "add to existing stacks" hotkey for inside chests as this presents the same issue.

**Comment by ParadoxiKat** [comment]
The delete key for trash is a base game feature, not a stardew access feature. As a result others before us have come across -- and resolved -- this same issue.
The following two mods fill this role:
1. Organize Inventory Shortcut: adds configurable hotkeys for organize inventory and add to stacks buttons for chests. Best match for this particular request. https://www.nexusmods.com/stardewvalley/mods/4772
2. Stash Items: Lets you configure a hotkey to add items to stacks in all near by chests without opening them. An area of attack add to stacks if you will. https://www.nexusmods.com/stardewvalley/mods/9624
