### ISSUE TITLE
Break out guides.md into multiple pages

### ISSUE THREAD

**Issue by PepperTheVixen** [stardew-access/stardew-access#391]
docs/guides.md contains a lot of useful info on how to play Stardew Valley blind, but the file is becoming very long and hard to read. The section about farming contains multiple headings and subheadings already and doesn't cover every aspect of farming. I have turned my effort to working on a mining guide, however that is complex enough that it will significantly increase the length of guides.md even more. It's difficult to edit such a large file too.

I propose that it be broken out into multiple files in its own directory with easy links on each file to jump around. This way, information is presented in smaller chunks to users: a page for using the mod proper, a page for socializing and events/festivals, a page for mining, a page for farming, a page for late game content like Ginger Island guides, etc.

EDIT: PR created https://github.com/khanshoaib3/stardew-access/pull/395

**Comment by khanshoaib3** [comment]
@PepperTheVixen I agree with this and I guess you're already working on this :)

**Comment by PepperTheVixen** [comment]
Relevant PR: https://github.com/khanshoaib3/stardew-access/pull/395
