### ISSUE TITLE
building from the current dev branch results in an unuseable options menu

### ISSUE THREAD

**Issue by danielw97** [stardew-access/stardew-access#398]
Hi there,
I'm building stardew access from the current dev branch, and one issue I've noticed right away is an unuseable options menu.
Running stardew valley 1.6.8, and when navigating to the options tab I receive numbers instead of the expected menu options.
I've reverted to v1.6.0-beta.5 for the moment as it doesn't have this problem, although I'm happy to test so please let me know if there's any more info you would like on this issue.

**Comment by khanshoaib3** [comment]
@danielw97  Try building from the `tile_properties` branch, should be fixed. And thanks for mentioning that, I was focusing on v1.6.9

**Comment by danielw97** [comment]
Thanks for your reply, building from that branch fixed it.
