### ISSUE TITLE
Compatibility with SdV 1.6.9

### ISSUE THREAD

**Issue by fz0308** [stardew-access/stardew-access#411]
I tried updating my SdV to 1.6.9 Beta, and apparently Stardew Access mod is no longer compatible with it. Please update the mod as I'm afraid the full SdV 1.6.9 release is also incompatible with the current version of Stardew Access.

**Comment by khanshoaib3** [comment]
The mod is updated for v1.6.9, I've just commented out the v1.6.9 specific changes. I can share the v1.6.9 build with you though.

**Comment by khanshoaib3** [comment]
@fz0308 Sorry for posting after two weeks, here's a compatible nightly build: https://github.com/khanshoaib3/stardew-access/actions/runs/11652279409/artifacts/2138023892
