### ISSUE TITLE
Stardew Access Mod No Longer Loads in Smapi

### ISSUE THREAD

**Issue by GloriousMysticalDawn** [stardew-access/stardew-access#415]
As of today, Stardew Access no longer loads in Smapi. I get a message that says that Stardew Access cannot load because it is no longer compatible. I tried updating to the latest version of Smapi and reinstalling the Stardew Access mod, but nothing is working. I am thinking that either an update in Stardew Valley or in Smapi is causing Stardew Access not to load when the game is launched through Steam and Smapi. 
Thank you,
Misty

**Comment by LucieG0** [comment]
Hi, you need to use the version of smapi that is compatible with Stardew valley 1.6.9, and use the latest build of Stardew access. Try grabbing it from here.

https://github.com/khanshoaib3/stardew-access/actions/runs/11669483473/artifacts/2142343284
