### ISSUE TITLE
Character Creation Interaction Bug

### ISSUE THREAD

**Issue by Bartholomue** [stardew-access/stardew-access#47]
1.3.2 won't interact with the text edit areas any more with control + enter. Verified by reverting to 1.3.1 where it still works fine. I wonder if it's conflicting with pressing enter to break out of text edits -- by breaking out immediately since it detects the enter key??

**Comment by khanshoaib3** [comment]
Fixed as of 52c8b6e3e3be46d2a11239cb3145d7bc8e5075c9
