### ISSUE TITLE
busy stones

### ISSUE THREAD

**Issue by TrueBlindGaming** [stardew-access/stardew-access#9]
in the latest beta 1.0.11. regular stones read as "busy stones". this alos holds for tables being "harvestable" if they have a decrative item placed on them

**Comment by TrueBlindGaming** [comment]
I have created a possible solution. it gets rid of all the mistakes except just regular stones outside the mines, since they are under the "category.others" along with  the machines. I created a pull request if you want to use my solution at all
https://github.com/stardew-access/stardew-access/pull/11

**Comment by shoaib11120** [comment]
Fixed it, added regular stones to debris category
